# Alembic Configuration
# =======================

[alembic]
# Path to migration scripts.
script_location = migrations

# Template used to generate migration file names.
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(rev)s_%%(slug)s

# Timezone to use when rendering the date.
timezone = UTC

# If true, add content of revisions to the version_locations.
prepend_sys_path = .

# Version path separator.
version_path_separator = os

# Don't output "Generating..." etc.
output_encoding = utf-8

# Don't add sys.path.
truncate_slug_length = 40

sqlalchemy.url = %(SYNC_DATABASE_URL)s


[post_write_hooks]
# Post write hooks are run after generating or autogenerating a revision.
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -q

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
